<?php

namespace Lazytask\Services;

class TransStrings
{
    /**
     * Return an array of UI strings, translated via __('...').
     *
     * Each string follows the format:
     * 'String' => __('String', 'lazytasks-project-task-management')
     *
     * If a string needs context for translators, add a comment above it.
     */
    public static function getStrings()
    {
        return [
            // Navigation
            'Dashboard' => __('Dashboard', 'lazytasks-project-task-management'),
            'My Tasks' => __('My Tasks', 'lazytasks-project-task-management'),
            'My Zen' => __('My Zen', 'lazytasks-project-task-management'),
            'Portal' => __('Portal', 'lazytasks-project-task-management'),
            'Mobile App' => __('Mobile App', 'lazytasks-project-task-management'),
            'Workspace' => __('Workspace', 'lazytasks-project-task-management'),
            'Profile' => __('Profile', 'lazytasks-project-task-management'),
            'Settings' => __('Settings', 'lazytasks-project-task-management'),
            'Logout' => __('Logout', 'lazytasks-project-task-management'),

            // Dashboard Cards
            'Project Summary' => __('Project Summary', 'lazytasks-project-task-management'),
            'Project Summary Chart' => __('Project Summary Chart', 'lazytasks-project-task-management'),
            'Quick Tasks' => __('Quick Tasks', 'lazytasks-project-task-management'),
            'All' => __('All', 'lazytasks-project-task-management'),
            'Overdue' => __('Overdue', 'lazytasks-project-task-management'),
            'OVERDUE' => __('OVERDUE', 'lazytasks-project-task-management'),
            'Today' => __('Today', 'lazytasks-project-task-management'),
            '7 Days' => __('7 Days', 'lazytasks-project-task-management'),
            'Upcoming' => __('Upcoming', 'lazytasks-project-task-management'),
            'Add Quick Task' => __('Add Quick Task', 'lazytasks-project-task-management'),
            'Add Quick Tasks' => __('Add Quick Tasks', 'lazytasks-project-task-management'),
            'Active' => __('Active', 'lazytasks-project-task-management'),
            'Complete' => __('Complete', 'lazytasks-project-task-management'),
            'Completed' => __('Completed', 'lazytasks-project-task-management'),
            'ACTIVE' => __('ACTIVE', 'lazytasks-project-task-management'),
            'COMPLETED' => __('COMPLETED', 'lazytasks-project-task-management'),
            'Chart' => __('Chart', 'lazytasks-project-task-management'),
            'Calendar' => __('Calendar', 'lazytasks-project-task-management'),

            // Quick Task Section
            'You have no quick tasks at the moment.' => __('You have no quick tasks at the moment.', 'lazytasks-project-task-management'),
            'Let\'s create one and become more efficient.' => __('Let\'s create one and become more efficient.', 'lazytasks-project-task-management'),
            'Never forget a task however small it is!' => __('Never forget a task however small it is!', 'lazytasks-project-task-management'),

            // Feedback & Support
            'Feedback' => __('Feedback', 'lazytasks-project-task-management'),
            'Premium Support' => __('Premium Support', 'lazytasks-project-task-management'),
            'Connect with Founder' => __('Connect with Founder', 'lazytasks-project-task-management'),
            'Write a Review' => __('Write a Review', 'lazytasks-project-task-management'),
            'About' => __('About', 'lazytasks-project-task-management'),
            'About LazyTasks' => __('About LazyTasks', 'lazytasks-project-task-management'),
            'Version' => __('Version', 'lazytasks-project-task-management'),
            'Developed by' => __('Developed by', 'lazytasks-project-task-management'),
            'Website' => __('Website', 'lazytasks-project-task-management'),
            'LazyTasks is brought to you by LazyCoders Inc., designed to streamline communication and project management. Combining ease of use with powerful features, we\'re committed to enhancing your collaborative experience.' => __('LazyTasks is brought to you by LazyCoders Inc., designed to streamline communication and project management. Combining ease of use with powerful features, we\'re committed to enhancing your collaborative experience.', 'lazytasks-project-task-management'),
            'For support or feedback, please visit our website or contact us at' => __('For support or feedback, please visit our website or contact us at', 'lazytasks-project-task-management'),

            // Translators comments
            /* translators: %d is the number of users engaged */
            '%d users engaged' => __('%d users engaged', 'lazytasks-project-task-management'),
            /* translators: %d is the number of task */
            '%d task' => __('%d task', 'lazytasks-project-task-management'),

            // Views
            'List' => __('List', 'lazytasks-project-task-management'),
            'Board' => __('Board', 'lazytasks-project-task-management'),
            'Calendar' => __('Calendar', 'lazytasks-project-task-management'),
            'Gantt Chart' => __('Gantt Chart', 'lazytasks-project-task-management'),
            'Gantt chart' => __('Gantt chart', 'lazytasks-project-task-management'),
            'Refresh Tasks' => __('Refresh Tasks', 'lazytasks-project-task-management'),
            'Refresh Section' => __('Refresh Section', 'lazytasks-project-task-management'),
            'Refresh' => __('Refresh', 'lazytasks-project-task-management'),
            'No tasks available to display the Gantt chart.' => __('No tasks available to display the Gantt chart.', 'lazytasks-project-task-management'),
            'You can add tasks on gantt chart from list tab.' => __('You can add tasks on gantt chart from list tab.', 'lazytasks-project-task-management'),
            'Alpha Release' => __('Alpha Release', 'lazytasks-project-task-management'),
            'Swimlane' => __('Swimlane', 'lazytasks-project-task-management'),
            'Whiteboard' => __('Whiteboard', 'lazytasks-project-task-management'), 
            'Beta' => __('Beta', 'lazytasks-project-task-management'),
            'Coming Soon' => __('Coming Soon', 'lazytasks-project-task-management'),
            'Search' => __('Search', 'lazytasks-project-task-management'),
            'Add Task to Gantt Chart' => __('Add Task to Gantt Chart', 'lazytasks-project-task-management'),
            'Remove Task From Gantt Chart' => __('Remove Task From Gantt Chart', 'lazytasks-project-task-management'),
            'Are you sure you want to remove task from gantt chart ?' => __('Are you sure you want to remove task from gantt chart ?', 'lazytasks-project-task-management'),
            'Are you sure you want to Add Task to Gantt Chart ?' => __('Are you sure you want to Add Task to Gantt Chart ?', 'lazytasks-project-task-management'),
            'Add to Gantt' => __('Add to Gantt', 'lazytasks-project-task-management'),
            'Remove from Gantt' => __('Remove from Gantt', 'lazytasks-project-task-management'),
            'Add All to Gantt' => __('Add All to Gantt', 'lazytasks-project-task-management'),
            'Remove All from Gantt' => __('Remove All from Gantt', 'lazytasks-project-task-management'),
            'Do you want to remove all tasks from Gantt?' => __('Do you want to remove all tasks from Gantt?', 'lazytasks-project-task-management'),
            'Group By' => __('Group By', 'lazytasks-project-task-management'),
            'Section' => __('Section', 'lazytasks-project-task-management'),
            'Priority' => __('Priority', 'lazytasks-project-task-management'),
            'Status' => __('Status', 'lazytasks-project-task-management'),
            'Assigned To' => __('Assigned To', 'lazytasks-project-task-management'),
            'Due Date' => __('Due Date', 'lazytasks-project-task-management'),

            // Keyboard Shortcuts
            'Keyboard Shortcuts' => __('Keyboard Shortcuts', 'lazytasks-project-task-management'),
            'Inline Task Edit' => __('Inline Task Edit', 'lazytasks-project-task-management'),
            'View Task Details Drawer' => __('View Task Details Drawer', 'lazytasks-project-task-management'),
            'Close Inline Task Popups' => __('Close Inline Task Popups', 'lazytasks-project-task-management'),
            'Close Task Details Drawer' => __('Close Task Details Drawer', 'lazytasks-project-task-management'),
            'Create New Task' => __('Create New Task', 'lazytasks-project-task-management'),
            'Focus Task Search Field' => __('Focus Task Search Field', 'lazytasks-project-task-management'),
            'Open Project Dropdown' => __('Open Project Dropdown', 'lazytasks-project-task-management'),
            'Go to Dashboard' => __('Go to Dashboard', 'lazytasks-project-task-management'),
            'Go to My Tasks' => __('Go to My Tasks', 'lazytasks-project-task-management'),
            'Switch Views (List → Board → Calendar → Gantt)' => __('Switch Views (List → Board → Calendar → Gantt)', 'lazytasks-project-task-management'),
            'Open Notifications' => __('Open Notifications', 'lazytasks-project-task-management'),

            // --- Additional unique UI strings from components ---
            /* translators: %d is the number of task */
            '%d tasks' => __('%d tasks', 'lazytasks-project-task-management'),
            /* translators: %d is the number people , invited, tag */
            '%d people invited' => __('%d people invited', 'lazytasks-project-task-management'),
            /* translators: %d is the number people */
            '%d people available' => __('%d people available', 'lazytasks-project-task-management'),
            /* translators: %d is the number tag */
            '%d tag available' => __('%d tag available', 'lazytasks-project-task-management'),

            // Task Table
            'Ref.#' => __('Ref.#', 'lazytasks-project-task-management'),
            'Task Title' => __('Task Title', 'lazytasks-project-task-management'),
            'Assigned' => __('Assigned', 'lazytasks-project-task-management'),
            'Following' => __('Following', 'lazytasks-project-task-management'),
            'Due Date' => __('Due Date', 'lazytasks-project-task-management'),
            'Date' => __('Date', 'lazytasks-project-task-management'),
            'Priority' => __('Priority', 'lazytasks-project-task-management'),
            'Status' => __('Status', 'lazytasks-project-task-management'),
            'Tags' => __('Tags', 'lazytasks-project-task-management'),
            'Assign Tag' => __('Assign Tag', 'lazytasks-project-task-management'),
            'Attachments' => __('Attachments', 'lazytasks-project-task-management'),
            'Created By' => __('Created By', 'lazytasks-project-task-management'),

            // Add Task Drawer
            'Type task name here' => __('Type task name here', 'lazytasks-project-task-management'),
            'Create' => __('Create', 'lazytasks-project-task-management'),
            'Type name here' => __('Type name here', 'lazytasks-project-task-management'),

            // Gantt Chart
            'Display on gantt' => __('Display on gantt', 'lazytasks-project-task-management'),

            // Search
            'Search...' => __('Search...', 'lazytasks-project-task-management'),
            'Quick search member' => __('Quick search member', 'lazytasks-project-task-management'),

            // Project Creation
            'Enter your project name' => __('Enter your project name', 'lazytasks-project-task-management'),
            'Select Workspace' => __('Select Workspace', 'lazytasks-project-task-management'),
            'Project name' => __('Project name', 'lazytasks-project-task-management'),
            'Configure Tabs' => __('Configure Tabs', 'lazytasks-project-task-management'),
            'View Archive Tasks/Sections' => __('View Archive Tasks/Sections', 'lazytasks-project-task-management'),
            'Project Settings' => __('Project Settings', 'lazytasks-project-task-management'),
            'Collapse Sections' => __('Collapse Sections', 'lazytasks-project-task-management'),
            'Expand Sections' => __('Expand Sections', 'lazytasks-project-task-management'),
            'Invite By Email' => __('Invite By Email', 'lazytasks-project-task-management'),
            'Invite' => __('Invite', 'lazytasks-project-task-management'),

            // Actions
            'Update' => __('Update', 'lazytasks-project-task-management'),
            'Delete' => __('Delete', 'lazytasks-project-task-management'),
            'Create' => __('Create', 'lazytasks-project-task-management'),
            'Send Invite' => __('Send Invite', 'lazytasks-project-task-management'),
            'Invited' => __('Invited', 'lazytasks-project-task-management'),
            'Submit' => __('Submit', 'lazytasks-project-task-management'),
            'Type name here' => __('Type name here', 'lazytasks-project-task-management'),
            'Type your comment here' => __('Type your comment here', 'lazytasks-project-task-management'),
            'What is the task about...' => __('What is the task about...', 'lazytasks-project-task-management'),

            // Color Toggles
            'Color' => __('Color', 'lazytasks-project-task-management'),
            'ON' => __('ON', 'lazytasks-project-task-management'),
            'OFF' => __('OFF', 'lazytasks-project-task-management'),

            // Pagination
            'Load More' => __('Load More', 'lazytasks-project-task-management'),

            // Task Completion
            'Mark as complete' => __('Mark as complete', 'lazytasks-project-task-management'),

            // Archive Section
            'Archive Section' => __('Archive Section', 'lazytasks-project-task-management'),
            'Archive all task' => __('Archive all task', 'lazytasks-project-task-management'),
            'Add All Tasks to Gantt' => __('Add All Tasks to Gantt', 'lazytasks-project-task-management'),
            'Remove All Tasks from Gantt' => __('Remove All Tasks from Gantt', 'lazytasks-project-task-management'),
            'Remove from Gantt' => __('Remove from Gantt', 'lazytasks-project-task-management'),

            // Task 3-dot menu
            'Add Task' => __('Add Task', 'lazytasks-project-task-management'),
            'Add Subtask' => __('Add Subtask', 'lazytasks-project-task-management'),
            'View Task' => __('View Task', 'lazytasks-project-task-management'),
            'View Subtask' => __('View Subtask', 'lazytasks-project-task-management'),
            'Complete Task' => __('Complete Task', 'lazytasks-project-task-management'),
            'Change Section' => __('Change Section', 'lazytasks-project-task-management'),
            'Archive Task' => __('Archive Task', 'lazytasks-project-task-management'),
            'Convert to Task' => __('Convert to Task', 'lazytasks-project-task-management'),
            'Enable reference numbers for tasks?' => __('Enable reference numbers for tasks?', 'lazytasks-project-task-management'),
            'Task Reference Number' => __('Task Reference Number', 'lazytasks-project-task-management'),
            'Reference number cannot be empty' => __('Reference number cannot be empty', 'lazytasks-project-task-management'),
            'Reference number cannot be 0' => __('Reference number cannot be 0', 'lazytasks-project-task-management'),
            'Reference number cannot be greater than 4000' => __('Reference number cannot be greater than 4000', 'lazytasks-project-task-management'),
            'Enter a starting number (1–500). Once set, it can\'t be changed.' => __('Enter a starting number (1–500). Once set, it can\'t be changed.', 'lazytasks-project-task-management'),
            'Complete Subtask' => __('Complete Subtask', 'lazytasks-project-task-management'),
            'Are you sure you want to complete this subtask?' => __('Are you sure you want to complete this subtask?', 'lazytasks-project-task-management'),
            'Incomplete' => __('Incomplete', 'lazytasks-project-task-management'),
            'Are you sure you want to incomplete this subtask?' => __('Are you sure you want to incomplete this subtask?', 'lazytasks-project-task-management'),
            'Incomplete Subtask' => __('Incomplete Subtask', 'lazytasks-project-task-management'),

            // API Config
            'API URL' => __('API URL', 'lazytasks-project-task-management'),
            'Enter api url' => __('Enter api url', 'lazytasks-project-task-management'),
            'API Key' => __('API Key', 'lazytasks-project-task-management'),
            'Enter api key' => __('Enter api key', 'lazytasks-project-task-management'),
            'API Secret Key' => __('API Secret Key', 'lazytasks-project-task-management'),
            'Enter api secret key' => __('Enter api secret key', 'lazytasks-project-task-management'),
            'Sender Name' => __('Sender Name', 'lazytasks-project-task-management'),
            'Enter sender name' => __('Enter sender name', 'lazytasks-project-task-management'),
            'SMS Settings' => __('SMS Settings', 'lazytasks-project-task-management'),
            'License Warning' => __('License Warning', 'lazytasks-project-task-management'),
            'Update LazyTasks Whiteboard Addons' => __('Update LazyTasks Whiteboard Addons', 'lazytasks-project-task-management'),

            // General Actions
            'Add' => __('Add', 'lazytasks-project-task-management'),
            'Remove' => __('Remove', 'lazytasks-project-task-management'),
            'Assign' => __('Assign', 'lazytasks-project-task-management'),
            'Follow' => __('Follow', 'lazytasks-project-task-management'),
            'YES' => __('YES', 'lazytasks-project-task-management'),
            'NO' => __('NO', 'lazytasks-project-task-management'),
            'to' => __('to', 'lazytasks-project-task-management'),
            'is deleted.' => __('is deleted.', 'lazytasks-project-task-management'),
            'for this task' => __('for this task', 'lazytasks-project-task-management'),

            // --- ViewArchive component strings ---
            'Archived Items' => __('Archived Items', 'lazytasks-project-task-management'),
            'Archived Tasks' => __('Archived Tasks', 'lazytasks-project-task-management'),
            'Archived Task' => __('Archived Task', 'lazytasks-project-task-management'),
            'Archived Sections' => __('Archived Sections', 'lazytasks-project-task-management'),
            'Unarchive Task' => __('Unarchive Task', 'lazytasks-project-task-management'),
            'Are you sure you want to unarchive this task?' => __('Are you sure you want to unarchive this task?', 'lazytasks-project-task-management'),
            'Unarchive' => __('Unarchive', 'lazytasks-project-task-management'),
            'Cancel' => __('Cancel', 'lazytasks-project-task-management'),
            'Task' => __('Task', 'lazytasks-project-task-management'),
            'Unarchiving The Task...' => __('Unarchiving The Task...', 'lazytasks-project-task-management'),
            'Delete Task' => __('Delete Task', 'lazytasks-project-task-management'),
            'Are you sure you want to permanently delete this task? This action cannot be undone.' => __('Are you sure you want to permanently delete this task? This action cannot be undone.', 'lazytasks-project-task-management'),
            'Deleting The Task...' => __('Deleting The Task...', 'lazytasks-project-task-management'),
            'Unarchiving Section...' => __('Unarchiving Section...', 'lazytasks-project-task-management'),
            'No archived tasks' => __('No archived tasks', 'lazytasks-project-task-management'),
            'No archived sections' => __('No archived sections', 'lazytasks-project-task-management'),
            'Archieved Sections' => __('Archieved Sections', 'lazytasks-project-task-management'),
            'Search archived sections...' => __('Search archived sections...', 'lazytasks-project-task-management'),
            'Search archived tasks...' => __('Search archived tasks...', 'lazytasks-project-task-management'),
            'Assign to' => __('Assign to', 'lazytasks-project-task-management'),
            'Filter Tasks' => __('Filter Tasks', 'lazytasks-project-task-management'),
            'Sections' => __('Sections', 'lazytasks-project-task-management'),
            'Select Sections' => __('Select Sections', 'lazytasks-project-task-management'),
            'Select Priority' => __('Select Priority', 'lazytasks-project-task-management'),
            'Select Status' => __('Select Status', 'lazytasks-project-task-management'),
            'Select' => __('Select', 'lazytasks-project-task-management'),
            'Reset Filters' => __('Reset Filters', 'lazytasks-project-task-management'),
            'Apply Filters' => __('Apply Filters', 'lazytasks-project-task-management'),

            // Settings
            'General' => __('General', 'lazytasks-project-task-management'),
            'Workspace & Projects' => __('Workspace & Projects', 'lazytasks-project-task-management'),
            'Roles & Permissions' => __('Roles & Permissions', 'lazytasks-project-task-management'),
            'Notification Templates' => __('Notification Templates', 'lazytasks-project-task-management'),
            'License' => __('License', 'lazytasks-project-task-management'),
            'Notification' => __('Notification', 'lazytasks-project-task-management'),
            'General Settings' => __('General Settings', 'lazytasks-project-task-management'),
            'Portal Settings' => __('Portal Settings', 'lazytasks-project-task-management'),
            'Roles & Permission' => __('Roles & Permission', 'lazytasks-project-task-management'),
            'Manage Tags' => __('Manage Tags', 'lazytasks-project-task-management'),
            'Task Reference No' => __('Task Reference No', 'lazytasks-project-task-management'),
            'Portal Title' => __('Portal Title', 'lazytasks-project-task-management'),
            'Portal Logo' => __('Portal Logo', 'lazytasks-project-task-management'),
            'Upload Portal Logo' => __('Upload Portal Logo', 'lazytasks-project-task-management'),
            'Image size should be 160 X 160' => __('Image size should be 160 X 160', 'lazytasks-project-task-management'),
            'Select Timezone' => __('Select Timezone', 'lazytasks-project-task-management'),
            'Enable frontend portal for easy access?' => __('Enable frontend portal for easy access?', 'lazytasks-project-task-management'),
            /* translators: %d is the number of project */
            '%d project' => __('%d project', 'lazytasks-project-task-management'),
            /* translators: %d is the number of project */
            '%d projects' => __('%d projects', 'lazytasks-project-task-management'),
            /* translators: %s is the string of base url */
            'Frontend Portal URL %s' => __('Frontend Portal URL %s', 'lazytasks-project-task-management'),
            'Enter Portal Slug' => __('Enter Portal Slug', 'lazytasks-project-task-management'),
            'Notification Settings' => __('Notification Settings', 'lazytasks-project-task-management'),
            'Web App' => __('Web App', 'lazytasks-project-task-management'),
            'Email' => __('Email', 'lazytasks-project-task-management'),
            'Mobile' => __('Mobile', 'lazytasks-project-task-management'),
            'Browser' => __('Browser', 'lazytasks-project-task-management'),

            // Tags/Roles
            'Add New Tag' => __('Add New Tag', 'lazytasks-project-task-management'),
            'Tag Name' => __('Tag Name', 'lazytasks-project-task-management'),
            '+ Add New Role' => __('+ Add New Role', 'lazytasks-project-task-management'),
            'Permission' => __('Permission', 'lazytasks-project-task-management'),
            'Create New Role' => __('Create New Role', 'lazytasks-project-task-management'),
            'Enter role name' => __('Enter role name', 'lazytasks-project-task-management'),
            'Role Name' => __('Role Name', 'lazytasks-project-task-management'),
            'Create Role' => __('Create Role', 'lazytasks-project-task-management'),

            // Roles & Permissions
            'Super Admin' => __('Super Admin', 'lazytasks-project-task-management'),
            'Admin' => __('Admin', 'lazytasks-project-task-management'),
            'Manager' => __('Manager', 'lazytasks-project-task-management'),
            'Add New Role' => __('Add New Role', 'lazytasks-project-task-management'),
            'Permission' => __('Permission', 'lazytasks-project-task-management'),
            'Save Changes' => __('Save Changes', 'lazytasks-project-task-management'),

            // Tag Deletion
            'Confirm Tag Deletion' => __('Confirm Tag Deletion', 'lazytasks-project-task-management'),
            'This tag is used in tasks. Deleting it will remove the tag from all associated tasks.Are you sure you want to delete this tag?' => __('This tag is used in tasks. Deleting it will remove the tag from all associated tasks.Are you sure you want to delete this tag?', 'lazytasks-project-task-management'),

            // Dashboard Cards
            'Total Tasks' => __('Total Tasks', 'lazytasks-project-task-management'),
            'Total Assigned Tasks' => __('Total Assigned Tasks', 'lazytasks-project-task-management'),
            'Complete Tasks' => __('Complete Tasks', 'lazytasks-project-task-management'),
            'Tasks Completed' => __('Tasks Completed', 'lazytasks-project-task-management'),
            'Pending Tasks' => __('Pending Tasks', 'lazytasks-project-task-management'),
            'Overdue Tasks' => __('Overdue Tasks', 'lazytasks-project-task-management'),
            'Name' => __('Name', 'lazytasks-project-task-management'),
            'Comp.' => __('Comp.', 'lazytasks-project-task-management'),
            'Total' => __('Total', 'lazytasks-project-task-management'),
            'Delete Quick Task' => __('Delete Quick Task', 'lazytasks-project-task-management'),
            'More...' => __('More...', 'lazytasks-project-task-management'),
            'No Task Found' => __('No Task Found', 'lazytasks-project-task-management'),
            'No tasks available' => __('No tasks available', 'lazytasks-project-task-management'),
            'Tasks In Progress' => __('Tasks In Progress', 'lazytasks-project-task-management'),
            'Task Distribution Matrix (By Project)' => __('Task Distribution Matrix (By Project)', 'lazytasks-project-task-management'),
            'Priority & Status Overview' => __('Priority & Status Overview', 'lazytasks-project-task-management'),
            'My Projects' => __('My Projects', 'lazytasks-project-task-management'),
            'Recent Activities' => __('Recent Activities', 'lazytasks-project-task-management'),
            'No recent activities found.' => __('No recent activities found.', 'lazytasks-project-task-management'),
            'User Engagement Scatter Plot' => __('User Engagement Scatter Plot', 'lazytasks-project-task-management'),

            // Quick Notes
            'Have something in mind? Thinking of something?' => __('Have something in mind? Thinking of something?', 'lazytasks-project-task-management'),
            'Jot it down here quickly before you forget.' => __('Jot it down here quickly before you forget.', 'lazytasks-project-task-management'),
            'Ensure every task, note, or idea is safely recorded!' => __('Ensure every task, note, or idea is safely recorded!', 'lazytasks-project-task-management'),
            'Convert it to a full blown task later at your convenience.' => __('Convert it to a full blown task later at your convenience.', 'lazytasks-project-task-management'),
            'Happy Tasking 🚀' => __('Happy Tasking 🚀', 'lazytasks-project-task-management'),
            'Add Quick Tasks' => __('Add Quick Tasks', 'lazytasks-project-task-management'),
            'Enter Task Title' => __('Enter Task Title', 'lazytasks-project-task-management'),
            'Are you Sure to delete this quick task ?' => __('Are you Sure to delete this quick task ?', 'lazytasks-project-task-management'),

            // Confirmations
            'You are parmanently deleting this quick task' => __('You are parmanently deleting this quick task', 'lazytasks-project-task-management'),
            'Are you Sure?' => __('Are you Sure?', 'lazytasks-project-task-management'),
            'Yes' => __('Yes', 'lazytasks-project-task-management'),
            'No' => __('No', 'lazytasks-project-task-management'),
            'Okay' => __('Okay', 'lazytasks-project-task-management'),

            // Time
            'Day' => __('Day', 'lazytasks-project-task-management'),
            'Week' => __('Week', 'lazytasks-project-task-management'),
            'Month' => __('Month', 'lazytasks-project-task-management'),

            // Sections/Subtasks
            '+ Add Section' => __('+ Add Section', 'lazytasks-project-task-management'),
            '+ Add Subtask' => __('+ Add Subtask', 'lazytasks-project-task-management'),
            'Add Section' => __('Add Section', 'lazytasks-project-task-management'),
            'You are archiving this section all task' => __('You are archiving this section all task', 'lazytasks-project-task-management'),
            'Are you sure you want to archive this section all task?' => __('Are you sure you want to archive this section all task?', 'lazytasks-project-task-management'),
            'Confirm' => __('Confirm', 'lazytasks-project-task-management'),
            'This section is currently marked as complete' => __('This section is currently marked as complete', 'lazytasks-project-task-management'),
            'You are archiving this section' => __('You are archiving this section', 'lazytasks-project-task-management'),
            'Are you sure you want to archive this section?' => __('Are you sure you want to archive this section?', 'lazytasks-project-task-management'),
            'You are parmanently deleting this section' => __('You are parmanently deleting this section', 'lazytasks-project-task-management'),
            'Are you sure you want to delete this section?' => __('Are you sure you want to delete this section?', 'lazytasks-project-task-management'),
            'Are you sure you want to convert this subtask as task?' => __('Are you sure you want to convert this subtask as task?', 'lazytasks-project-task-management'),

            // Dates
            'Start Date' => __('Start Date', 'lazytasks-project-task-management'),
            'Due Date' => __('Due Date', 'lazytasks-project-task-management'),
            'Save' => __('Save', 'lazytasks-project-task-management'),
            'Clear' => __('Clear', 'lazytasks-project-task-management'),
            '+ Create' => __('+ Create', 'lazytasks-project-task-management'),
            'Use Date Range' => __('Use Date Range', 'lazytasks-project-task-management'),

            // Priority/Status
            'You are parmanently deleting this priority' => __('You are parmanently deleting this priority', 'lazytasks-project-task-management'),
            'Are you sure you want to delete this priority?' => __('Are you sure you want to delete this priority?', 'lazytasks-project-task-management'),
            'You are parmanently deleting this status' => __('You are parmanently deleting this status', 'lazytasks-project-task-management'),
            'Are you sure you want to delete this status?' => __('Are you sure you want to delete this status?', 'lazytasks-project-task-management'),

            /* translators: %d is the number of tags */
            'More (%d)' => __('More (%d)', 'lazytasks-project-task-management'),
            'Pick tag from list' => __('Pick tag from list', 'lazytasks-project-task-management'),

            // Comments/Activities
            'Only Comments' => __('Only Comments', 'lazytasks-project-task-management'),
            'Only Activities' => __('Only Activities', 'lazytasks-project-task-management'),
            'Comments & Activities' => __('Comments & Activities', 'lazytasks-project-task-management'),
            'Comment' => __('Comment', 'lazytasks-project-task-management'),
            'No Activities' => __('No Activities', 'lazytasks-project-task-management'),
            'Not found...' => __('Not found...', 'lazytasks-project-task-management'),
            'Are you sure this comment delete?' => __('Are you sure this comment delete?', 'lazytasks-project-task-management'),
            'You are parmanently deleting this comment' => __('You are parmanently deleting this comment', 'lazytasks-project-task-management'),

            // Workspaces/Projects/Members
            'Workspace' => __('Workspace', 'lazytasks-project-task-management'),
            'Workspaces' => __('Workspaces', 'lazytasks-project-task-management'),
            'Projects' => __('Projects', 'lazytasks-project-task-management'),
            'Members' => __('Members', 'lazytasks-project-task-management'),
            'Create Workspace' => __('Create Workspace', 'lazytasks-project-task-management'),
            'Create Project' => __('Create Project', 'lazytasks-project-task-management'),
            'Add Member' => __('Add Member', 'lazytasks-project-task-management'),
            'Workspace name' => __('Workspace name', 'lazytasks-project-task-management'),
            'You are parmanently deleting this workspace' => __('You are parmanently deleting this workspace', 'lazytasks-project-task-management'),
            'Are you sure you want to delete this workspace?' => __('Are you sure you want to delete this workspace?', 'lazytasks-project-task-management'),
            'Edit Project' => __('Edit Project', 'lazytasks-project-task-management'),
            'Wordpress Users' => __('Wordpress Users', 'lazytasks-project-task-management'),
            'Added' => __('Added', 'lazytasks-project-task-management'),
            'Template List' => __('Template List', 'lazytasks-project-task-management'),
            'You haven\'t been assigned to a specific workspace or project yet.' => __('You haven\'t been assigned to a specific workspace or project yet.', 'lazytasks-project-task-management'),

            // Integrations
            'SMTP Configuration' => __('SMTP Configuration', 'lazytasks-project-task-management'),
            'SMTP Mode' => __('SMTP Mode', 'lazytasks-project-task-management'),
            'Use Wordpress default' => __('Use Wordpress default', 'lazytasks-project-task-management'),
            'Use this SMTP' => __('Use this SMTP', 'lazytasks-project-task-management'),
            'WordPress default mailer will be used for notifications.' => __('WordPress default mailer will be used for notifications.', 'lazytasks-project-task-management'),
            'SMTP Host' => __('SMTP SMTP Host', 'lazytasks-project-task-management'),
            'Enter SMTP Host' => __('Enter host', 'lazytasks-project-task-management'),
            'Username' => __('Username', 'lazytasks-project-task-management'),
            'Enter Username' => __('Enter Username', 'lazytasks-project-task-management'),
            'Password' => __('Password', 'lazytasks-project-task-management'),
            'Enter Password' => __('Enter Password', 'lazytasks-project-task-management'),
            'Sender Name' => __('Sender Name', 'lazytasks-project-task-management'),
            'Enter Sender Name' => __('Enter Sender Name', 'lazytasks-project-task-management'),
            'Sender Email' => __('Sender Email', 'lazytasks-project-task-management'),
            'Enter Sender Email' => __('Enter Sender Email', 'lazytasks-project-task-management'),
            'SMTP Port' => __('SMTP Port', 'lazytasks-project-task-management'),
            'Enter SMTP Port' => __('Enter SMTP Port', 'lazytasks-project-task-management'),
            'SMS Configuration' => __('SMS Configuration', 'lazytasks-project-task-management'),
            'Recommended Plugin WP SMS is active' => __('Recommended Plugin WP SMS is active', 'lazytasks-project-task-management'),
            'Recommended Plugin WP SMS is not installed' => __('Recommended Plugin WP SMS is not installed', 'lazytasks-project-task-management'),
            'SMS Notifications' => __('SMS Notifications', 'lazytasks-project-task-management'),
            'Send SMS notifications to users for various events.' => __('Send SMS notifications to users for various events.', 'lazytasks-project-task-management'),
            'Firebase Configuration' => __('Firebase Configuration', 'lazytasks-project-task-management'),
            'SMTP Notifications' => __('SMTP Notifications', 'lazytasks-project-task-management'),
            'Send Email notifications to users for various events.' => __('Send Email notifications to users for various events.', 'lazytasks-project-task-management'),

            // Notification Templates
            'Title' => __('Title', 'lazytasks-project-task-management'),
            'Channel' => __('Channel', 'lazytasks-project-task-management'),
            'Do action hook' => __('Do action hook', 'lazytasks-project-task-management'),
            'Add New Notification Template' => __('Add New Notification Template', 'lazytasks-project-task-management'),
            'Create Template' => __('Create Template', 'lazytasks-project-task-management'),
            'Update Template' => __('Update Template', 'lazytasks-project-task-management'),
            'Enable/Disable' => __('Enable/Disable', 'lazytasks-project-task-management'),
            /* translators: %s is the string of channel name */
            'Enter %s content here' => __('Enter %s content here', 'lazytasks-project-task-management'),
            'Email subject' => __('Email subject', 'lazytasks-project-task-management'),
            'Enter email subject' => __('Enter email subject', 'lazytasks-project-task-management'),
            'Notification title' => __('Notification title', 'lazytasks-project-task-management'),
            'Enter notification title' => __('Enter notification title', 'lazytasks-project-task-management'),
            'Message body' => __('Message body', 'lazytasks-project-task-management'),
            'Template Variables' => __('Template Variables', 'lazytasks-project-task-management'),
            'NAME' => __('NAME', 'lazytasks-project-task-management'),
            'User\'s Name' => __('User\'s Name', 'lazytasks-project-task-management'),
            'USERNAME' => __('USERNAME', 'lazytasks-project-task-management'),
            'USERNAME (login credentials)' => __('USERNAME (login credentials)', 'lazytasks-project-task-management'),
            'LOGIN_URL' => __('LOGIN_URL', 'lazytasks-project-task-management'),
            'The sign-in link for the app or workspace' => __('The sign-in link for the app or workspace', 'lazytasks-project-task-management'),
            'PASSWORD' => __('PASSWORD', 'lazytasks-project-task-management'),
            'PASSWORD (login credentials)' => __('PASSWORD (login credentials)', 'lazytasks-project-task-management'),
            'MEMBER_NAME' => __('MEMBER_NAME', 'lazytasks-project-task-management'),
            'Member Name' => __('Member Name', 'lazytasks-project-task-management'),
            'COMPANY_NAME' => __('COMPANY_NAME', 'lazytasks-project-task-management'),
            'Workspace Name' => __('Workspace Name', 'lazytasks-project-task-management'),
            'PROJECT_NAME' => __('PROJECT_NAME', 'lazytasks-project-task-management'),
            'Project Name' => __('Project Name', 'lazytasks-project-task-management'),
            'CREATOR_NAME' => __('CREATOR_NAME', 'lazytasks-project-task-management'),
            'Creator Name' => __('Creator Name', 'lazytasks-project-task-management'),
            'MEMBER_ROLES' => __('MEMBER_ROLES', 'lazytasks-project-task-management'),
            'Member Role' => __('Member Role', 'lazytasks-project-task-management'),
            'TASK_NAME' => __('TASK_NAME', 'lazytasks-project-task-management'),
            'Task Name' => __('Task Name', 'lazytasks-project-task-management'),
            'PREVIOUS_ASSIGNED_DATE' => __('PREVIOUS_ASSIGNED_DATE', 'lazytasks-project-task-management'),
            'Previous Assigned Date' => __('Previous Assigned Date', 'lazytasks-project-task-management'),
            'NEW_ASSIGNED_DATE' => __('NEW_ASSIGNED_DATE', 'lazytasks-project-task-management'),
            'New Assigned Date' => __('New Assigned Date', 'lazytasks-project-task-management'),
            'Do action title' => __('Do action title', 'lazytasks-project-task-management'),
            'Enter your title' => __('Enter your title', 'lazytasks-project-task-management'),
            'Do action (hook)' => __('Do action (hook)', 'lazytasks-project-task-management'),
            'Enter action name' => __('Enter action name', 'lazytasks-project-task-management'),

            // Notification
            'Unread' => __('Unread', 'lazytasks-project-task-management'),
            'All' => __('All', 'lazytasks-project-task-management'),
            'Mark all as read' => __('Mark all as read', 'lazytasks-project-task-management'),
            'just now' => __('just now', 'lazytasks-project-task-management'),
            'minute ago' => __('minute ago', 'lazytasks-project-task-management'),
            'minutes ago' => __('minutes ago', 'lazytasks-project-task-management'),
            'hour ago' => __('hour ago', 'lazytasks-project-task-management'),
            'hours ago' => __('hours ago', 'lazytasks-project-task-management'),
            'day ago' => __('day ago', 'lazytasks-project-task-management'),
            'days ago' => __('days ago', 'lazytasks-project-task-management'),
            'month ago' => __('month ago', 'lazytasks-project-task-management'),
            'months ago' => __('months ago', 'lazytasks-project-task-management'),
            'year ago' => __('year ago', 'lazytasks-project-task-management'),
            'years ago' => __('years ago', 'lazytasks-project-task-management'),

            // Privacy
            'Make Private' => __('Make Private', 'lazytasks-project-task-management'),
            'Make Public' => __('Make Public', 'lazytasks-project-task-management'),

            // Duplicates
            'Duplicate Task' => __('Duplicate Task', 'lazytasks-project-task-management'),
            'Duplicate Section' => __('Duplicate Section', 'lazytasks-project-task-management'),

            // Addons
            'Addons' => __('Addons', 'lazytasks-project-task-management'),
            'LazyTasks Whiteboard' => __('LazyTasks Whiteboard', 'lazytasks-project-task-management'),
            'Add a collaborative whiteboard to your task management plugin for visual brainstorming and real-time teamwork.' => __('Add a collaborative whiteboard to your task management plugin for visual brainstorming and real-time teamwork.', 'lazytasks-project-task-management'),
            'Install & Activate Whiteboard' => __('Install & Activate Whiteboard', 'lazytasks-project-task-management'),
            'Activate Addon' => __('Activate Addon', 'lazytasks-project-task-management'),
            'Activate Social Login' => __('Activate Social Login', 'lazytasks-project-task-management'),
            'Deactivate Whiteboard' => __('Deactivate Whiteboard', 'lazytasks-project-task-management'),
            'LazyTasks Social Login' => __('LazyTasks Social Login', 'lazytasks-project-task-management'),
            'Enable users to log in using their social media accounts, simplifying the authentication process and enhancing user experience.' => __('Enable users to log in using their social media accounts, simplifying the authentication process and enhancing user experience.', 'lazytasks-project-task-management'),
            'You do not have permission to deactivate addons.' => __('You do not have permission to deactivate addons.', 'lazytasks-project-task-management'),
            'Please contact your administrator to deactivate the addon.' => __('Please contact your administrator to deactivate the addon.', 'lazytasks-project-task-management'),
            'Please activate social login from Addons' => __('Please activate social login from Addons', 'lazytasks-project-task-management'),
            'Install LazyTasks Whiteboard Addons' => __('Install LazyTasks Whiteboard Addons', 'lazytasks-project-task-management'),

            // Social Login
            'Social Login' => __('Social Login', 'lazytasks-project-task-management'),
            'Google Login' => __('Google Login', 'lazytasks-project-task-management'),
            'Login with Google' => __('Login with Google', 'lazytasks-project-task-management'),
            'Enable users to log in using their Google account.' => __('Enable users to log in using their Google account.', 'lazytasks-project-task-management'),
            'Client ID' => __('Client ID', 'lazytasks-project-task-management'),
            'Enter Client ID' => __('Enter Client ID', 'lazytasks-project-task-management'),
            'Client Secret' => __('Client Secret', 'lazytasks-project-task-management'),
            'Enter Client Secret' => __('Enter Client Secret', 'lazytasks-project-task-management'),
            'Login with Facebook' => __('Login with Facebook', 'lazytasks-project-task-management'),
            'Enable users to log in using their Facebook account.' => __('Enable users to log in using their Facebook account.', 'lazytasks-project-task-management'),
            'Login with LinkedIn' => __('Login with LinkedIn', 'lazytasks-project-task-management'),
            'Enable users to log in using their LinkedIn account.' => __('Enable users to log in using their LinkedIn account.', 'lazytasks-project-task-management'),
            'Deactivate Social Login' => __('Deactivate Social Login', 'lazytasks-project-task-management'),
            

            // Profile
            'Upload Profile Picture' => __('Upload Profile Picture', 'lazytasks-project-task-management'),
            'Image size should be 100 X 100' => __('Image size should be 100 X 100', 'lazytasks-project-task-management'),
            'First Name' => __('First Name', 'lazytasks-project-task-management'),
            'Last Name' => __('Last Name', 'lazytasks-project-task-management'),
            'Select Role' => __('Select Role', 'lazytasks-project-task-management'),
            'Phone' => __('Phone', 'lazytasks-project-task-management'),
            'Email' => __('Email', 'lazytasks-project-task-management'),
            'Edit Profile' => __('Edit Profile', 'lazytasks-project-task-management'),
            'Change Password' => __('Change Password', 'lazytasks-project-task-management'),
            'Current Password' => __('Current Password', 'lazytasks-project-task-management'),
            'New Password' => __('New Password', 'lazytasks-project-task-management'),
            'Confirm Password' => __('Confirm Password', 'lazytasks-project-task-management'),
            'Update Password' => __('Update Password', 'lazytasks-project-task-management'),
            'Edit Member' => __('Edit Member', 'lazytasks-project-task-management'),
            'Reset Password' => __('Reset Password', 'lazytasks-project-task-management'),
            'First name is required' => __('First name is required', 'lazytasks-project-task-management'),
            'Last name is required' => __('Last name is required', 'lazytasks-project-task-management'),
            'Email is required' => __('Email is required', 'lazytasks-project-task-management'),
            'Invalid email' => __('Invalid email', 'lazytasks-project-task-management'),
            'Invalid phone number' => __('Invalid phone number', 'lazytasks-project-task-management'),

            // Configuration Project
            'Default' => __('Default', 'lazytasks-project-task-management'),
            'Configure Project Tabs' => __('Configure Project Tabs', 'lazytasks-project-task-management'),
            'Manage your project tasks in a detailed list view.' => __('Manage your project tasks in a detailed list view.', 'lazytasks-project-task-management'),
            'Organize your tasks with a Kanban-style board.' => __('Organize your tasks with a Kanban-style board.', 'lazytasks-project-task-management'),
            'View your tasks on a calendar to track deadlines.' => __('View your tasks on a calendar to track deadlines.', 'lazytasks-project-task-management'),
            'Plan and schedule your project with a Gantt chart.' => __('Plan and schedule your project with a Gantt chart.', 'lazytasks-project-task-management'),
            'Visualize your project tasks on a whiteboard.' => __('Visualize your project tasks on a whiteboard.', 'lazytasks-project-task-management'),
            'Swimlanes to organize and streamline tasks' => __('Swimlanes to organize and streamline tasks', 'lazytasks-project-task-management'),
            'You do not have permission to configure project tabs.' => __('You do not have permission to configure project tabs.', 'lazytasks-project-task-management'),
            'Organize tasks into swimlanes for better workflow management.' => __('Organize tasks into swimlanes for better workflow management.', 'lazytasks-project-task-management'),

            // Archive Project
            'Archive Project' => __('Archive Project', 'lazytasks-project-task-management'),
            'Are you sure you want to archive this project?' => __('Are you sure you want to archive this project?', 'lazytasks-project-task-management'),
            'This project is archived' => __('This project is archived', 'lazytasks-project-task-management'),
            'Unarchive Project' => __('Unarchive Project', 'lazytasks-project-task-management'),
            'Are you sure you want to unarchive this project?' => __('Are you sure you want to unarchive this project?', 'lazytasks-project-task-management'),

            // Project Priority & Status
            'Critical' => __('Critical', 'lazytasks-project-task-management'),
            'High' => __('High', 'lazytasks-project-task-management'),
            'Medium' => __('Medium', 'lazytasks-project-task-management'),
            'Low' => __('Low', 'lazytasks-project-task-management'),
            'Active' => __('Active', 'lazytasks-project-task-management'),
            'In Progress' => __('In Progress', 'lazytasks-project-task-management'),
            'Completed' => __('Completed', 'lazytasks-project-task-management'),

            // Mobile App Modal
            'How to download and connect “LazyTasks” mobile app with installed plugin' => __('How to download and connect “LazyTasks” mobile app with installed plugin', 'lazytasks-project-task-management'),
            'Welcome to LazyTasks Premium' => __('Welcome to LazyTasks Premium', 'lazytasks-project-task-management'),
            'Activate Your Free Trial!' => __('Activate Your Free Trial!', 'lazytasks-project-task-management'),
            'Go Premium. Go Mobile.' => __('Go Premium. Go Mobile.', 'lazytasks-project-task-management'),
            'Upgrade now to use the iOS & Android apps fully, get real-time task updates, and organize projects more effectively across your team on-the-go.' => __('Upgrade now to use the iOS & Android apps fully, get real-time task updates, and organize projects more effectively across your team on-the-go.', 'lazytasks-project-task-management'),
            'Visit us at' => __('Visit us at', 'lazytasks-project-task-management'),
            'Activate Premium Access' => __('Activate Premium Access', 'lazytasks-project-task-management'),
            'Your trial is about to expire' => __('Your trial is about to expire', 'lazytasks-project-task-management'),
            'Purchase Now' => __('Purchase Now', 'lazytasks-project-task-management'),
            'Power Up Your Productivity Through LazyTasks Mobile' => __('Power Up Your Productivity Through LazyTasks Mobile', 'lazytasks-project-task-management'),
            'Download LazyTasks Mobile App' => __('Download LazyTasks Mobile App', 'lazytasks-project-task-management'),
            'Connect Your LazyTasks Mobile App' => __('Connect Your LazyTasks Mobile App', 'lazytasks-project-task-management'),

            // Other Strings
            'Remove?' => __('Remove?', 'lazytasks-project-task-management'),
            'Are you sure you want to remove from this project?' => __('Are you sure you want to remove from this project?', 'lazytasks-project-task-management'),
            'This action cannot be undone' => __('This action cannot be undone', 'lazytasks-project-task-management'),
            'Remove' => __('Remove', 'lazytasks-project-task-management'),
            'You do not have permission to manage priorities.' => __('You do not have permission to manage priorities.', 'lazytasks-project-task-management'),
            'You do not have permission to manage statuses.' => __('You do not have permission to manage statuses.', 'lazytasks-project-task-management'),
            'No members found' => __('No members found', 'lazytasks-project-task-management'),
            'Pro Feature' => __('Pro Feature', 'lazytasks-project-task-management'),
            'Firebase Notifications' => __('Firebase Notifications', 'lazytasks-project-task-management'),
            'Send Push notifications to users for various events.' => __('Send Push notifications to users for various events.'),
            'Client Email' => __('Client Email', 'lazytasks-project-task-management'),
            'Enter Client Email' => __('Enter Client Email', 'lazytasks-project-task-management'),
            'Private Key' => __('Private Key', 'lazytasks-project-task-management'),
            'Enter Private Key' => __('Enter Private Key', 'lazytasks-project-task-management'),
            'Permissions Updated' => __('Permissions Updated', 'lazytasks-project-task-management'),
            'The permissions have been applied.' => __('The permissions have been applied.', 'lazytasks-project-task-management'),
            'The users have to login again for it to take effect.' => __('The users have to login again for it to take effect.', 'lazytasks-project-task-management'),
            'Please advice your users accordingly.' => __('Please advice your users accordingly.', 'lazytasks-project-task-management'),

            // For Mobile App
            'Server List' => __('Server List', 'lazytasks-project-task-management'),
            'Scan QR Code' => __('Scan QR Code', 'lazytasks-project-task-management'),
            'Add server via QR Code' => __('Add server via QR Code', 'lazytasks-project-task-management'),
            'Point your camera at a QR code to instantly add a new Server' => __('Point your camera at a QR code to instantly add a new Server', 'lazytasks-project-task-management'),
            'View more' => __('View more', 'lazytasks-project-task-management'),
            'Completed Task' => __('Completed Task', 'lazytasks-project-task-management'),
            'Pending Task' => __('Pending Task', 'lazytasks-project-task-management'),
            'Overdue Task' => __('Overdue Task', 'lazytasks-project-task-management'),
            'Total Task' => __('Total Task', 'lazytasks-project-task-management'),
            'Total' => __('Total', 'lazytasks-project-task-management'),
            'Name Active Completed' => __('Name Active Completed', 'lazytasks-project-task-management'),
            'Write a task name' => __('Write a task name', 'lazytasks-project-task-management'),
            'Assign to' => __('Assign to', 'lazytasks-project-task-management'),
            'Description' => __('Description', 'lazytasks-project-task-management'),
            'Write a subtask name' => __('Write a subtask name', 'lazytasks-project-task-management'),
            'Attachment' => __('Attachment', 'lazytasks-project-task-management'),
            'No due date' => __('No due date', 'lazytasks-project-task-management'),
            'Task updated successfully' => __('Task updated successfully', 'lazytasks-project-task-management'),
            'No match found' => __('No match found', 'lazytasks-project-task-management'),
            'Close' => __('Close', 'lazytasks-project-task-management'),
        ];
    }
}